version: "3.8"

services:

  # Reverse proxy
  traefik:
    # Static configuration of Traefik
    environment:
      # Entrypoints
      - TRAEFIK_ENTRYPOINTS_websecure_ADDRESS=:443

      # Catch-all redirection from http to https
      - TRAEFIK_ENTRYPOINTS_web_HTTP_REDIRECTIONS_ENTRYPOINT_TO=websecure
      - TRAEFIK_ENTRYPOINTS_web_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME=https

      # TLS certificate through Let's Encrypt
      - TRAEFIK_CERTIFICATESRESOLVERS_leresolver=true
      - TRAEFIK_CERTIFICATESRESOLVERS_leresolver_ACME_EMAIL=${PONTOS_ACME_EMAIL}
      - TRAEFIK_CERTIFICATESRESOLVERS_leresolver_ACME_HTTPCHALLENGE=true
      - TRAEFIK_CERTIFICATESRESOLVERS_leresolver_ACME_HTTPCHALLENGE_ENTRYPOINT=web
      - TRAEFIK_CERTIFICATESRESOLVERS_leresolver_ACME_STORAGE=/letsencrypt/acme.json
      #- TRAEFIK_CERTIFICATESRESOLVERS_leresolver_ACME_CASERVER=https://acme-staging-v02.api.letsencrypt.org/directory

    ports:
      - "${PONTOS_HUB_HTTPS_PORT:-443}:443"

    volumes:
      - "./letsencrypt:/letsencrypt"

  # MQTT broker
  emqx:
    labels:
      - "traefik.http.routers.emqx-ws.entryPoints=websecure"
      - "traefik.http.routers.emqx-ws.rule=Host(`${PONTOS_HOST}`) && PathPrefix(`/mqtt`)"
      - "traefik.http.routers.emqx-ws.tls.certresolver=leresolver"

  # REST api
  api:
    labels:
      - "traefik.http.routers.postgrests.entryPoints=websecure"
      - "traefik.http.routers.postgrest.rule=Host(`${PONTOS_HOST}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.postgrest.tls.certresolver=leresolver"

  # REST api
  swagger:
    labels:
      - "traefik.http.routers.swagger.entryPoints=websecure"
      - "traefik.http.routers.swagger.rule=Host(`${PONTOS_HOST}`) && PathPrefix(`/docs`)"
      - "traefik.http.routers.swagger.tls.certresolver=leresolver"
