version: "3.8"

services:

  # Reverse proxy
  traefik:
    command:
      - "--log.level=INFO"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--providers.docker.constraints=Label(`pontos.expose`, `true`)"

      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.traefik-dashboard.address=:8080"
      - "--entrypoints.emqx-dashboard.address=:8081"

      # Catch-all redirection from http to https
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"

      # TLS certificate through Let's Encrypt
      - "--certificatesresolvers.LEresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.LEresolver.acme.httpchallenge.entrypoint=web"
      #      - "--certificatesresolvers.LEresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.LEresolver.acme.email=${PONTOS_HUB_ACME_EMAIL}"
      - "--certificatesresolvers.LEresolver.acme.storage=/letsencrypt/acme.json"

    # Static configuration of Traefik
    environment:
      # Entrypoints
      - TRAEFIK_ENTRYPOINTS_websecure_ADDRESS=:443

      # Catch-all redirection from http to https
      - TRAEFIK_ENTRYPOINTS_web_HTTP_REDIRECTIONS_ENTRYPOINT_TO=websecure
      - TRAEFIK_ENTRYPOINTS_web_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME=https

    ports:
      - "${PONTOS_HUB_EXTERNAL_HTTPS_PORT:-443}:443"

    volumes:
      - "./letsencrypt:/letsencrypt"
