version: "3.8"

services:

  # Reverse proxy
  traefik:
    image: "traefik:v2.9"
    restart: unless-stopped

    # Static configuration of Traefik
    environment:
      # General configuration
      - TRAEFIK_LOG_LEVEL=${PONTOS_TRAEFIK_LOG_LEVEL:-ERROR}
      - TRAEFIK_ACCESSLOG=true
      - TRAEFIK_API_DASHBOARD=true
      - TRAEFIK_PROVIDERS_DOCKER=true
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=true
      - TRAEFIK_PROVIDERS_DOCKER_CONSTRAINTS=Label(`pontos.expose`, `true`)

      # Entrypoints
      - TRAEFIK_ENTRYPOINTS_web_ADDRESS=:80
      - TRAEFIK_ENTRYPOINTS_traefik-dashboard_ADDRESS=:8080
      - TRAEFIK_ENTRYPOINTS_emqx-dashboard_ADDRESS=:8081

    # Dynamic configuration for exposing Traefik's dashboard an api on separate endpoints
    labels:
      - "pontos.expose=true"
      - "traefik.http.routers.traefik-dashboard.rule=(PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.traefik-dashboard.entryPoints=traefik-dashboard"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
    ports:
      - "${PONTOS_HUB_HTTP_PORT:-80}:80"
      - "${PONTOS_TRAEFIK_DASHBOARD_PORT:-8080}:8080"
      - "${PONTOS_EMQX_DASHBOARD_PORT:-8081}:8081"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  # MQTT broker
  emqx:
    image: emqx/emqx:5.0.20
    restart: unless-stopped
    environment:
      - EMQX_NAME=pontos-hub
      - EMQX_HOST=127.0.0.1
      - EMQX_RETAINER__BACKEND__STORAGE_TYPE=disc
      - EMQX_LOG__CONSOLE_HANDLER__ENABLE=true
      - EMQX_LOG__CONSOLE_HANDLER__LEVEL=${PONTOS_EMQX_LOG_LEVEL:-warning}
    labels:
      - "pontos.expose=true"
      - "traefik.http.routers.emqx-ws.rule=PathPrefix(`/mqtt`)"
      - "traefik.http.routers.emqx-ws.entryPoints=web"
      - "traefik.http.routers.emqx-ws.service=emqx-ws-service"
      - "traefik.http.services.emqx-ws-service.loadbalancer.server.port=8083"
      - "traefik.tcp.routers.emqx-dashboard.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.emqx-dashboard.entryPoints=emqx-dashboard"
      - "traefik.tcp.routers.emqx-dashboard.service=emqx-dashboard-service"
      - "traefik.tcp.services.emqx-dashboard-service.loadbalancer.server.port=18083"
    volumes:
      - vol-emqx-data:/opt/emqx/data

  # Database
  db:
    image: timescale/timescaledb:2.10.1-pg15
    restart: unless-stopped
    environment:
      POSTGRES_DB: pontos
      POSTGRES_USER: pontos_user
      POSTGRES_PASSWORD: ${PONTOS_DB_PASSWORD}
    volumes:
      # Data volume
      - vol-pg-data:/var/lib/postgresql/data
      # Initialization scripts
      - ./database/docker-entrypoint-initdb.d/010-pontos-setup.sql:/docker-entrypoint-initdb.d/010-pontos-setup.sql
      - ./database/docker-entrypoint-initdb.d/011-pontos-example-data.sql:/docker-entrypoint-initdb.d/011-pontos-example-data.sql
      - ./database/docker-entrypoint-initdb.d/012-pontos-postgrest-setup.sql:/docker-entrypoint-initdb.d/012-pontos-postgrest-setup.sql
      - ./database/docker-entrypoint-initdb.d/013-pontos-postgrest-authenticator-setup.sh:/docker-entrypoint-initdb.d/013-pontos-postgrest-authenticator-setup.sh

  # REST api
  api:
    image: postgrest/postgrest:v10.2.0
    restart: unless-stopped
    environment:
      - PGRST_DB_URI=postgres://authenticator:${PONTOS_DB_PASSWORD}@db:5432/pontos
      - PGRST_OPENAPI_SERVER_PROXY_URI=http://localhost/api
      - PGRST_DB_SCHEMAS=api_views
      - PGRST_DB_ANON_ROLE=web_user # Has read permissions!
    depends_on:
      - db
    labels:
      - "pontos.expose=true"
      - "traefik.http.routers.postgrest.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.postgrest.entryPoints=web"
      - "traefik.http.routers.postgrest.service=postgrest-service"
      - "traefik.http.services.postgrest-service.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.postgrest-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.postgrest-ratelimit.ratelimit.average=1"
      - "traefik.http.middlewares.postgrest-ratelimit.ratelimit.period=10s"
      - "traefik.http.routers.postgrest.middlewares=postgrest-stripprefix@docker"

  # Swagger api docs
  swagger:
    image: swaggerapi/swagger-ui:v4.18.1
    restart: unless-stopped
    environment:
      - API_URL=/api
      - BASE_URL=/docs
    depends_on:
      - api
    labels:
      - "pontos.expose=true"
      - "traefik.http.routers.swagger.rule=PathPrefix(`/docs`)"
      - "traefik.http.routers.swagger.entryPoints=web"
      - "traefik.http.routers.swagger.service=swagger-service"
      - "traefik.http.services.swagger-service.loadbalancer.server.port=8080"

  # Data ingestor
  ingestor:
    image: ghcr.io/mo-rise/pontos-data-ingestor:v0.0.2
    restart: unless-stopped
    environment:
      - MQTT_BROKER_HOST=emqx
      - MQTT_BROKER_PORT=1883
      - MQTT_BASE_TOPIC=PONTOS/#
      - PG_CONNECTION_STRING=postgres://pontos_user:${PONTOS_DB_PASSWORD}@db:5432/pontos
      - PG_TABLE_NAME=vessel_data.master
      - PG_POOL_SIZE=3
      - PARTITION_SIZE=100
      - PARTITION_TIMEOUT=5
    depends_on:
      - emqx
      - db

volumes:
  vol-emqx-data:
  vol-pg-data:
