version: "3.8"

services:

  # Reverse proxy
  traefik:
    # Static configuration of Traefik
    environment:
      # Entrypoints
      - TRAEFIK_ENTRYPOINTS_websecure_ADDRESS=:443

      # Catch-all redirection from http to https
      - TRAEFIK_ENTRYPOINTS_web_HTTP_REDIRECTIONS_ENTRYPOINT_TO=websecure
      - TRAEFIK_ENTRYPOINTS_web_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME=https

      # TLS certificate through Let's Encrypt
      - TRAEFIK_CERTIFICATESRESOLVER_LEresolver=true
      - TRAEFIK_CERTIFICATESRESOLVER_LEresolver_ACME_EMAIL=${PONTOS_HUB_ACME_EMAIL}
      - TRAEFIK_CERTIFICATESRESOLVER_LEresolver_ACME_HTTPCHALLENGE=true
      - TRAEFIK_CERTIFICATESRESOLVER_LEresolver_ACME_HTTPCHALLENGE_ENTRYPOINT=web
      - TRAEFIK_CERTIFICATESRESOLVER_LEresolver_ACME_STORAGE=/letsencrypt/acme.json
      #- TRAEFIK_CERTIFICATESRESOLVER_LEresolver_ACME_CASERVER=https://acme-staging-v02.api.letsencrypt.org/directory

    ports:
      - "${PONTOS_HUB_EXTERNAL_HTTPS_PORT:-443}:443"

    volumes:
      - "./letsencrypt:/letsencrypt"

  # MQTT broker
  emqx:
    labels:
      - "traefik.http.routers.emqx-ws.entryPoints=websecure"
      - "traefik.http.routers.emqx-ws.rule=Host(`${PONTOS_HUB_HOST}`) && PathPrefix(`/mqtt`)"
      - "traefik.http.routers.emqx-ws.tls.certresolver=LEresolver"
